# Generated by Django 5.0.6 on 2024-07-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='image',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
